apiVersion: v1
appVersion: 3.3.7
description: AWS X-Ray helps you debug and analyze your microservices applications with request tracing
home: https://aws.amazon.com/xray/
keywords:
  - aws
  - tracing
  - xray
maintainers:
  - email: okgolove@markeloff.net
    name: okgolove
name: aws-xray
sources:
  - https://github.com/aws/aws-xray-daemon
version: 4.0.3
